package org.prueba.model;
// Generated 27/02/2021 23:11:15 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * Especialista generated by hbm2java
 */
@Entity
@Table(name = "Especialista", schema = "dbo", catalog = "Prueba")
public class Especialista implements java.io.Serializable {

	private int idEspecialista;
	private String identificacion;
	private String nombre;
	private String apellido;
	private String email;
	private String direccion;
	private String telefono;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);

	public Especialista() {
	}

	public Especialista(int idEspecialista) {
		this.idEspecialista = idEspecialista;
	}

	public Especialista(int idEspecialista, String identificacion, String nombre, String apellido, String email,
			String direccion, String telefono, Set<Ticket> tickets) {
		this.idEspecialista = idEspecialista;
		this.identificacion = identificacion;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.direccion = direccion;
		this.telefono = telefono;
		this.tickets = tickets;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "IdEspecialista", unique = true, nullable = false)
	public int getIdEspecialista() {
		return this.idEspecialista;
	}

	public void setIdEspecialista(int idEspecialista) {
		this.idEspecialista = idEspecialista;
	}

	@Column(name = "Identificacion", length = 10)
	@Size(max = 10)
	public String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	@Column(name = "Nombre", length = 60)
	@Size(max = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Apellido", length = 60)
	@Size(max = 60)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "Email", length = 100)
	@Size(max = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Direccion", length = 200)
	@Size(max = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "Telefono", length = 15)
	@Size(max = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especialista")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

}
